### ISSUE TITLE
Submit to Zeek package source?

### ISSUE THREAD

**Issue by ckreibich** [sandialabs/gait#1]
Interesting package! Are you up for including it in Zeek's [package source](https://github.com/zeek/packages) so people find it more easily?

**Comment by csmutz** [comment]
Thanks for reaching out.

Why yes, yes we are. We are currently trying to make a new revision that we plan to promote more and provide upstream. We hope to release this soon, hopefully well before end of the calendar year. Some of the changes we are working on are paring down TLS metadata and adding SSH timing analysis. 

One of the ugliest things we are doing now is taking an incredibly painful path to get raw TCP header options (we need complete option list and order) but only on initial SYN packets. See tcp_options_kinds in tcp_attrs.zeek. Is there a better way? We’d love a callback that had raw TCP options for SYN packets only or even a better way to get TCP header offset from raw packets.

**Comment by Brathoma** [comment]
@ckreibich We have just submitted and been approved putting gait into zkg! Have there been any thoughts to Charles's question about getting some sort of TCP header options for SYN packets instead of us having to parse the packets ourselves?

**Comment by csmutz** [comment]
gait has been added zeek package source
