### ISSUE TITLE
octeon metadata extractor

### ISSUE THREAD

**Issue by FlorianHeigl** [sandialabs/gait#4]
Hi,

is this project related to https://www.osti.gov/servlets/purl/1863848 by any chance??
I was trying where to find the SE application from that paper - it could be related to this, or part of it, but i'm uncertain. The paper says things about open source but I didn't see if this was ever deemed worth releasing.

(Footnote: And it IS worth it! Why is this interesting? since for 'lower-than-sandia' levels of performance it sounds like a really really neat application. The cards have become more affordable, but noone on their own would have the ressources to develop a package like you did. Sandias test case for 40/100g was a 2/4-socket intel box, and the offload cards didn't match up against that, but say someone were to get one of the cards for $300 and would be able to skip on a huge pile of server just by that means, it would be a nice thing.)

**Comment by Brathoma** [comment]
This project is tangentially related to the project from that paper. We do not do any Deep Packet Inspection within this project but instead focus on the header information for packet analysis. 

But thank you for the appreciation. We really tried to focus on the improved performance for this level of analysis. We will be working on improving this project in the coming weeks as well.
